/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 25 14:09:15 GMT 2024
 */
package com.zappos.json.util;


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zappos.json.util.ObjectArray;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class ObjectArray_ESTest extends ObjectArray_ESTest_scaffolding {


@Test(timeout = 4000)
public void test02() throws Throwable {
    ObjectArray objectArray0 = new ObjectArray();
    objectArray0.modCount = (-837);
    int int0 = objectArray0.size();
    assertEquals(0, int0);
}


@Test(timeout = 4000)
public void test13() throws Throwable {
    ObjectArray objectArray0 = new ObjectArray();
    Object[] objectArray1 = new Object[0];
    objectArray0.elementData = objectArray1;
    objectArray0.add(objectArray0);
    Integer[] integerArray0 = new Integer[0];
    // Undeclared exception!
    try {
        objectArray0.toArray(integerArray0);
        fail("Expecting exception: ArrayStoreException");
    } catch (ArrayStoreException e) {
        // 
        // no message in exception (getMessage() returned null)
        // 
        verifyException("java.util.Arrays", e);
    }
}


@Test(timeout = 4000)
public void test04() throws Throwable {
    ObjectArray objectArray0 = new ObjectArray();
    objectArray0.modCount = (-2461);
    // Undeclared exception!
    try {
        objectArray0.get(2668);
        fail("Expecting exception: IndexOutOfBoundsException");
    } catch (IndexOutOfBoundsException e) {
        // 
        // Index: 2668, Size: 0
        // 
        verifyException("com.zappos.json.util.ObjectArray", e);
    }
}


@Test(timeout = 4000)
public void test01() throws Throwable {
    ObjectArray objectArray0 = new ObjectArray();
    objectArray0.modCount = 1492;
    // Undeclared exception!
    try {
        objectArray0.toArray();
        fail("Expecting exception: NullPointerException");
    } catch (NullPointerException e) {
        // 
        // no message in exception (getMessage() returned null)
        // 
    }
}

}
